### ISSUE TITLE
JumpKingPlus v1.8.0 crashes after few seconds in game.

### ISSUE THREAD

**Issue by WaldoAndFriends** [JumpKingPlus/JumpKingPlus#13]
![image](https://user-images.githubusercontent.com/77986224/164075473-3901ffaf-9846-4e66-bc54-6addadd7f67e.png)

**Comment by WaldoAndFriends** [comment]
Crash log:
```
System.MissingMethodException: Method not found: 'Void JumpKing.Sprite.Draw(Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Graphics.SpriteEffects)'.
   at JumpKingMod.Entities.RavenEntity.Draw()
   at JumpKingMod.Entities.Raven.MessengerRavenEntity.Draw() in D:\Documents\Git\JumpKingMod\JumpKingMod\JumpKingMod\Entities\Raven\MessengerRavenEntity.cs:line 213
   at JumpKingMod.Entities.ModEntityManager.Draw() in D:\Documents\Git\JumpKingMod\JumpKingMod\JumpKingMod\Entities\ModEntityManager.cs:line 72
   at EntityComponent.EntityManager.Draw_Patch1(EntityManager this)
   at JumpKing.JumpGame.Draw_Patch1(JumpGame this)
   at JumpKing.Game1.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at JumpKing.Program.Run()
System.MissingMethodException: Method not found: 'Void JumpKing.Sprite.Draw(Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Graphics.SpriteEffects)'.
   at JumpKingMod.Entities.RavenEntity.Draw()
   at JumpKingMod.Entities.Raven.MessengerRavenEntity.Draw() in D:\Documents\Git\JumpKingMod\JumpKingMod\JumpKingMod\Entities\Raven\MessengerRavenEntity.cs:line 213
   at JumpKingMod.Entities.ModEntityManager.Draw() in D:\Documents\Git\JumpKingMod\JumpKingMod\JumpKingMod\Entities\ModEntityManager.cs:line 72
   at EntityComponent.EntityManager.Draw_Patch1(EntityManager this)
   at JumpKing.JumpGame.Draw_Patch1(JumpGame this)
   at JumpKing.Game1.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at JumpKing.Program.Run()
System.MissingMethodException: Method not found: 'Void JumpKing.Sprite.Draw(Microsoft.Xna.Framework.Vector2, Microsoft.Xna.Framework.Graphics.SpriteEffects)'.
   at JumpKingMod.Entities.RavenEntity.Draw()
   at JumpKingMod.Entities.Raven.MessengerRavenEntity.Draw() in D:\Documents\Git\JumpKingMod\JumpKingMod\JumpKingMod\Entities\Raven\MessengerRavenEntity.cs:line 213
   at JumpKingMod.Entities.ModEntityManager.Draw() in D:\Documents\Git\JumpKingMod\JumpKingMod\JumpKingMod\Entities\ModEntityManager.cs:line 72
   at EntityComponent.EntityManager.Draw_Patch1(EntityManager this)
   at JumpKing.JumpGame.Draw_Patch1(JumpGame this)
   at JumpKing.Game1.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at JumpKing.Program.Run()
```

**Comment by PhantomBadger** [comment]
You need to upgrade JumpKing Chat Ravens to the newest pre-release (2.1a or newer)

https://github.com/PhantomBadger/JumpKing-TwitchRavens/releases/tag/v2.1a

**Comment by WaldoAndFriends** [comment]
> You need to upgrade JumpKing Chat Ravens to the newest pre-release (2.1a or newer)

Thanks, I'll try that tonight. Explains why the game crashed within seconds of me starting the game, as that's the time it took for a chat message to come in.

It might not be applicable to the majority of the users, but might be smart if a small notice could be included in the release entry here on GitHub.

**Comment by PhantomBadger** [comment]
Compatibility between mods is always a tricky balance, since the issue is with the reflection code in the Chat Ravens Mod no longer matching the Jump King game (since JK+ modifies the actual executable) I did opt to add a message to the top of the main README for the Chat Ravens: 
https://github.com/PhantomBadger/JumpKing-TwitchRavens#for-jk-v180-please-use-pre-release-v21a

And I'll be attempting to Future Proof some of the other code to better report when these kind of incompatibilities emerge in the future.
