### ISSUE TITLE
SteamJK stopped working

### ISSUE THREAD

**Issue by Yarady** [JumpKingPlus/JumpKingPlus#31]
Well, I installed Jump King Plus but it gave me an error. When i try opening the game from the executable after installation it simply crashes. Before i install the JKP, the game worked fine. Here is the CrashLog:

System.NullReferenceException: Object reference not set to an instance of an object.
   at LanguageJK.Program.LoadLanguageFromFile(String p_file)
   at JumpKing.Program.Run()

**Comment by Phoenixx19** [comment]
Hello.
May I get the full crash screenshot?

**Comment by iterus0** [comment]
I had the same error. Switching game to english solved it for me.

To change language you need to right click jump king in steam, select properties and language.

Alternatively you can edit language.xml config in the root folder of the game to:
```
<language>EnglishUS</language>
```
