### ISSUE TITLE
KeyNotFoundException upon selecting New Game

### ISSUE THREAD

**Issue by mrmaandi** [JumpKingPlus/JumpKingPlus#7]
I'm getting an error upon selecting New Game. It see the first level for 2 seconds and then it crashes. I downloaded Jump King on Steam, installed Jump King Plus (v1.5.2), downloaded Babe of Ascension latest version and put the files in the mods folder. Any idea what could be causing this?

> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at JumpKing.AmbienceManager.GetDistance(AmbienceTrack p_track)
   at JumpKing.AmbienceManager.LoadSounds()
   at JumpKing.AmbienceManager.Update(Single p_delta)
   at EntityComponent.Entity.UpdateComponents(Single p_delta)
   at EntityComponent.EntityManager.Update(Single p_delta)
   at JumpKing.JumpGame.Update(GameTime gameTime)
   at JumpKing.Game1.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at JumpKing.Program.Run()

**Comment by mrmaandi** [comment]
I seem to have gotten it working with Jump King Plus v1.5.1. It's either a problem with v1.5.2 or it was to do with something else, i have no clue

**Comment by Phoenixx19** [comment]
Will look into it.

**Comment by Phoenixx19** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/Phoenixx19/JumpKingPlus/issues/7](https://trello.com/c/BT0TTiYV/9-https-githubcom-phoenixx19-jumpkingplus-issues-7)
